---
title: Workfront Fusion：シナリオ接続エラー
description: 特定のシナリオの実行が失敗し、「接続を検証できませんでした」というエラーメッセージが表示されます。
hidefromtoc: true
feature: Workfront Fusion
exl-id: 53edb587-86ab-4515-90b3-c2a338eadfc3
source-git-commit: fc79f8aec41eaf077edccc2309ef86e4724c7787
workflow-type: ht
source-wordcount: '46'
ht-degree: 100%

---

# Workfront Fusion：シナリオ接続エラー

特定のシナリオの実行が失敗し、「接続を検証できませんでした」というエラーメッセージが表示されます。

_最初に報告されたのは 2025年2月19日（PT）です。_
